### ISSUE TITLE
Several issues caused by updating Pathfinder core system on foundry

### ISSUE THREAD

**Issue by Snuggly-Wuggums** [TikaelSol/PF2e-Kitsune-of-Golarion#1]
Hi, sorry to bother. I was wondering if there were plans to update to the most recent version of foundry/PF2e?

With the latest update to both, a variety of features have broken for the module.

Notably from my game

Nine Aura's doesn't actually interact with Foxfire anymore and can't be applied as a status to the person who has it.
The Kitsune Equipment compendium can't be opened in the compendium viewer
A couple scattered ancestry traits don't seem to be apply their boons: notably the Nimble Kitsune I've seen.

**Comment by TikaelSol** [comment]
Yes, I have not updated the module to migrate it to v10 yet. You can migrate it yourself by unlocking the compendiums, importing them, then exporting them back (uncheck the keep IDs checkbox otherwise links will break). I have several modules I need to update to v10, but system data entry takes priority and October is a big month for new entry with Kingmaker and Kobold King.

**Comment by Snuggly-Wuggums** [comment]
Appreciated thanks :)
